### ISSUE TITLE
Remove Debian

### ISSUE THREAD

**Issue by ArielSAdamsNASA** [core-flight-system/containers#5]
Remove `ENV DEBIAN_FRONTEND=noninteractive` as it is not needed.

**Comment by wbv** [comment]
That line prevents `apt` from trying to get user input during package installation, which can happen if certain dependencies (e.g. the `tzdata` package) get upgraded. Removing it is inconsequential until some combination of upstream packages are updated and then your Dockerfile might suddenly stall or fail during build. Was the behavior change causing problems elsewhere?

This issue response from one of the docker maintainers explains in a little more detail: https://github.com/docker/docs/issues/13980#issuecomment-997740982
